function [VarName1,id,date_time,gx,gy,gz,x_jerk,y_jerk,vec_mag,z_jerk,ms,gap,activity,intensity,flip1,line1] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME1,ID,DATE_TIME,GX,GY,GZ,X_JERK,Y_JERK,VEC_MAG,Z_JERK,MS,GAP,ACTIVITY,INTENSITY,FLIP1,LINE1]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [VARNAME1,ID,DATE_TIME,GX,GY,GZ,X_JERK,Y_JERK,VEC_MAG,Z_JERK,MS,GAP,ACTIVITY,INTENSITY,FLIP1,LINE1]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,id,date_time,gx,gy,gz,x_jerk,y_jerk,vec_mag,z_jerk,ms,gap,activity,intensity,flip1,line1] = importfile('3473_3_raw.csv',2, 34390);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/21 12:08:48

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%q)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: text (%q)
%	column14: text (%q)
%   column15: text (%q)
%	column16: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%q%f%f%f%f%f%f%f%f%f%f%q%q%q%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
id = dataArray{:, 2};
date_time = dataArray{:, 3};
gx = dataArray{:, 4};
gy = dataArray{:, 5};
gz = dataArray{:, 6};
x_jerk = dataArray{:, 7};
y_jerk = dataArray{:, 8};
vec_mag = dataArray{:, 9};
z_jerk = dataArray{:, 10};
ms = dataArray{:, 11};
gap = dataArray{:, 12};
activity = dataArray{:, 13};
intensity = dataArray{:, 14};
flip1 = dataArray{:, 15};
line1 = dataArray{:, 16};


